# F60 forward verdicts, assigned BY READING (see VERDICTS.md for the grounds).
V = [
 ("5.2","B10","LIVE-B","STALE","QUEUE","'B10 must therefore NOT remove the base-altitude workaround' — B10 is DONE 2026-07-22 (S11.71); the sentence addresses it prospectively"),
 ("5.5","A1","CLOSED-PTR","NOT-A-ROW","KEY","S11.73 Tier-A key `sidereal_time` (A1), not row A1"),
 ("5.5","A2","CLOSED-PTR","NOT-A-ROW","KEY","Tier-A key `shadow_color`"),
 ("5.5","A3","CLOSED-PTR","NOT-A-ROW","KEY","Tier-A key, delivered by S11.91 (A1/A2/A3/A4)"),
 ("5.5","A4","LIVE-A","NOT-A-ROW","KEY","Tier-A key (`CASE(\"Moon\",CUSTOM)` dead -> delete)"),
 ("5.5","A5","CLOSED-PTR","NOT-A-ROW","KEY","Tier-A key `isStar()`"),
 ("5.5","A6","CLOSED-PTR","NOT-A-ROW","KEY","Tier-A key `surface_model`"),
 ("5.5","A7","LIVE-A","NOT-A-ROW","KEY","Tier-A key `trail_length`"),
 ("5.5","A8","CLOSED-PTR","NOT-A-ROW","KEY","Tier-A key (G6 heuristic), 'A8/A9 type-keyed'"),
 ("5.5","A9","CLOSED-PTR","NOT-A-ROW","KEY","Tier-A key (G6 heuristic)"),
 ("5.5","B24","LIVE-B","COHERENT","QUEUE","inside the struck 'emit/consume -> B25/B24' span, superseded in place 2026-08-29"),
 ("5.5","B25","ARCHIVED","COHERENT","QUEUE","same struck span; B25 CLOSED 2026-07-30 and the row records the supersession above it"),
 ("5.5","B27","LIVE-B","COHERENT","QUEUE","'SUSPENDED on B27' — B27 live and open"),
 ("5.5","B4","LIVE-B","COHERENT","ARTIFACT","'the session-12 B4-row precedent' — a precedent, not a queue"),
 ("5.5","B5","LIVE-B","COHERENT","QUEUE","survivor homed at B5, which is live and open"),
 ("5.18","B10","LIVE-B","COHERENT","QUEUE","'MECHANISM FIXED by B10' — records B10's delivery; residual (floor VALUE) matches B10's own row"),
 ("5.19","B9","ARCHIVED","NON-STATE","PROVENANCE","'out-of-scope of B9 (found by it)' — a dated scoping fact; B9's closure cannot falsify it"),
 ("5.20","B24","LIVE-B","NON-STATE","PROVENANCE","'found by the B24 composition inventory'"),
 ("5.23","B24","LIVE-B","COHERENT","QUEUE","'implementation rides B24' (D18 logging) — B24 live and open"),
 ("5.24","B15","LIVE-B","COHERENT","ARTIFACT","'the class the B15 (AoI latch) and B19 (position freeze) fixes closed'"),
 ("5.24","B19","ARCHIVED","COHERENT","ARTIFACT","'rotation twin of the B19 position-freeze' — names the class"),
 ("5.24","B24","LIVE-B","NON-STATE","PROVENANCE","'found by the B24 equivalence A-vs-A control'"),
 ("5.24","B32","ARCHIVED","STALE","QUEUE","'OPEN -> ledger B32' — B32 is ROW DONE (fix LANDED 2026-07-24, code 2912d303, S11.93) and archived; the retired index line INSIDE the same file already reads FIXED by B32"),
 ("5.25","B14","LIVE-B","NON-STATE","PROVENANCE","'found by B14-periode 2026-07-23'"),
 ("5.26","A38","CLOSED-PTR","COHERENT","QUEUE","the row states 'A38 CLOSED' itself"),
 ("5.26","B17","LIVE-B","NON-STATE","PROVENANCE","'exposed by B17's offset'"),
 ("5.26","B21","LIVE-B","COHERENT","QUEUE","struck 'alongside B21's descent note' + SWEPT block"),
 ("5.26","B33","LIVE-B","COHERENT","QUEUE","'what remains of this row is ... the READOUT (B33)' — B33 live and open"),
 ("5.27","B15","LIVE-B","COHERENT","ARTIFACT","'the closed load-time-latch class (B15/B19/B32)' — calls them closed"),
 ("5.27","B19","ARCHIVED","COHERENT","ARTIFACT","same clause"),
 ("5.27","B3","LIVE-B","NON-STATE","PROVENANCE","'found by the F1/B3 root-cause chain, S11.100'"),
 ("5.27","B31","LIVE-B","COHERENT","QUEUE","'Also unblocked by the same answer: B31's T3' — B31 live and open"),
 ("5.27","B32","ARCHIVED","COHERENT","ARTIFACT","same closed-class clause"),
 ("5.28","A33","CLOSED-PTR","NON-STATE","PROVENANCE","'decision A33's referent' inside the F59 ID-REUSE note"),
 ("5.28","B14","LIVE-B","NON-STATE","PROVENANCE","'B14 rot_pole_w0 90 deg axis defect' inside the same note"),
 ("5.32","B15","LIVE-B","COHERENT","QUEUE","'closes ... the reference half of the B15 residual' — the row's own CLOSED block records it landed"),
 ("5.32","B35","LIVE-B","COHERENT","ARTIFACT","'B35's config-only class' — B35 live and open"),
 ("5.34","B24","LIVE-B","NON-STATE","PROVENANCE","'B24-select adds a second instance of the class'"),
 ("5.36","B38","LIVE-B","NON-STATE","PROVENANCE","'found by the F4 command-grammar census S11.108(k) / B38'"),
 ("5.41","B31","LIVE-B","NON-STATE","PROVENANCE","'found by the B31 design pass 2026-07-25'"),
 ("5.42","B31","LIVE-B","NON-STATE","PROVENANCE","'found by the B31 design pass 2026-07-25'"),
 ("5.43","B4","LIVE-B","NON-STATE","PROVENANCE","'MEASURED the first time ... (2026-07-25, the B4 anchor registry)'"),
 ("5.44","B39","LIVE-B","STALE","QUEUE","'The row exists so B39 does not port the old behaviour' — B39 DONE 2026-07-30 (S11.117) and its own row records 'S5.44 impossible here'; the guard purpose is discharged and this row does not say so"),
 ("5.46","B39","LIVE-B","AMBIGUOUS","QUEUE|ARTIFACT","'collapsing it is B39-barrier work' — reading (a) a routing to B39, which is DONE and cannot take it; reading (b) work that touches the barrier B39 built, which persists. Not resolved here"),
 ("5.50","A1","CLOSED-PTR","NOT-A-ROW","KEY","harness leg range: 'b24_screen stays green A1-A5'"),
 ("5.50","A5","CLOSED-PTR","NOT-A-ROW","KEY","same leg range"),
 ("5.52","B12","LIVE-B","NON-STATE","PROVENANCE","'Identical in the pre-B12 and post-B12 binaries'"),
 ("5.54","B12","LIVE-B","NON-STATE","PROVENANCE","'found ... while locating the regime boundary for B12'"),
 ("5.55","B7","LIVE-B","COHERENT","ARTIFACT","'a member of the S11.15d/B7 shutdown-crash class' — B7 live and open"),
 ("5.59","B17","LIVE-B","NON-STATE","PROVENANCE","'what S11.74 concluded about B17's mis-filed draw-stall'"),
 ("5.59","B7","LIVE-B","COHERENT","ARTIFACT","'every HUNG in the B7 record' — B7 live and open"),
 ("5.63","B10","LIVE-B","NOT-A-ROW","KEY","'the B10 line of f20_session.py's scene A' = b31-design §2 state row B10 (viewOffset), not ledger B10"),
 ("5.63","B19","ARCHIVED","NOT-A-ROW","KEY","'§2 row B19' = b31-design §2 state row B19 (old-path Observer/Navigator twin state), disambiguated by the author"),
 ("5.63","B31","LIVE-B","COHERENT","QUEUE","'the next B31 slice inherits it' — B31 live; the row's own later block corrects the T1 clause"),
 ("5.66","B9","ARCHIVED","COHERENT","ARTIFACT","'the B9 az-convention family (S11.4/S11.60)' — a named family, not a queue"),
 ("5.68","B33","LIVE-B","NON-STATE","PROVENANCE","'found 2026-08-01 by F23 while closing B33's read half'"),
 ("5.70","B28","ARCHIVED","COHERENT","ARTIFACT","'B28 owns command spellings' = the B28 PROTOCOL (new product surface needs sign-off), live vocabulary used by the owner himself 2026-08-26 (S11.154(b))"),
 ("5.71","B34","LIVE-B","COHERENT","QUEUE","'the last member of B34's class' — B34 live and open"),
 ("5.77","B28","ARCHIVED","COHERENT","ARTIFACT","'a new interface, B28-adjacent' — the same protocol reading"),
 ("5.80","B10","LIVE-B","NON-STATE","PROVENANCE","'B10/B21 measured their behaviour, not their frame'"),
 ("5.80","B21","LIVE-B","NON-STATE","PROVENANCE","same clause"),
 ("5.82","B28","ARCHIVED","COHERENT","ARTIFACT","'B28 also forbids minting around it' — the protocol reading"),
 ("5.85","B4","LIVE-B","COHERENT","QUEUE","'this is B4(iv)'s recorded derivation gap' — B4(iv) DELIVERED and its row routes align_with to §5.85; the pair is coherent BOTH ways"),
 ("5.86","B24","LIVE-B","NON-STATE","PROVENANCE","'a composed (B24) body'"),
 ("5.87","B3","LIVE-B","NOT-A-ROW","KEY","'[artifacts/f35/post/f35_result_post.json B3]' — a probe key inside an artifact citation"),
 ("5.88","B9","ARCHIVED","NOT-A-ROW","KEY","\"'Type spectral : B9p'\" — a star SPECTRAL TYPE in quoted program output"),
 ("5.89","B1","LIVE-B","AMBIGUOUS","QUEUE","'the RING/asteroid line (B1/S4)' — reading (a) the architectural line named by its head row (fable-dispatch §2 groups 'B1/S4 + B2 + riding rows'); reading (b) an imprecise cite for B2, which is the row that carries the RING asteroid. Both rows live and blocked, so no state move is implied"),
 ("5.100","B17","LIVE-B","NON-STATE","PROVENANCE","'the B17 view-offset mirror IS there, two lines below'"),
 ("5.104","B16","ARCHIVED","COHERENT","ARTIFACT","'rides B16's seam' — the SEAM B16 built (`body action reload`), not its queue; and the row's own FIXED-AND-CLOSED block (F41, S11.155) supersedes the routing"),
 ("5.104","B28","ARCHIVED","COHERENT","ARTIFACT","'ONE GATE: B28 sign-off on the new-format scaling key' — the protocol; DISCHARGED at S11.155(a) ('display_scale ADOPTED ... B28 verdict')"),
 ("5.107","B15","LIVE-B","COHERENT","ARTIFACT","'the closed B15/B19/B32/S11.152(b) class'"),
 ("5.107","B19","ARCHIVED","COHERENT","ARTIFACT","same clause"),
 ("5.107","B32","ARCHIVED","COHERENT","ARTIFACT","same clause"),
]
B = [
 ("A23","5.2","COHERENT","§5.2's claim REFUTED — matches §5.2's own record"),
 ("A30","5.40","COHERENT","names a failure mode; §5.40 is ARCHIVED (archived-read, flagged)"),
 ("A40","5.59","COHERENT","'§5.59's fork' — §5.59 live and open"),
 ("A41","5.54","COHERENT","recorded-column reference; §5.54 open"),
 ("A42","5.53","COHERENT","recorded-column reference; §5.53 open"),
 ("A43","5.53","COHERENT","recorded-column reference; §5.53 open"),
 ("B3","5.27","NON-STATE","dated decomposition (§11.100); the row's later blocks carry the state"),
 ("B3","5.29","COHERENT","'§5.29 is CLOSED' recorded in the row's PART 1 block (archived-read, flagged)"),
 ("B3","5.30","COHERENT","'§5.30 CLOSED' recorded in the PART 2 block (archived-read, flagged)"),
 ("B3","5.33","COHERENT","'§5.33 FOUND AND CLOSED' (archived-read, flagged)"),
 ("B4","5.41","COHERENT","§5.41 open"),
 ("B4","5.43","COHERENT","'fixed at the class: §5.43' — §5.43 FIXED"),
 ("B4","5.80","NON-STATE","'Five new §5 rows recorded, none fixed (§5.80-§5.85)' — a dated campaign record; §5.81 has since CLOSED (2026-08-09, §11.145). NEAR-MISS, see VERDICTS.md"),
 ("B4","5.85","COHERENT","'§5.85, which owns what the command is for' — §5.85 open; coherent BOTH ways"),
 ("B7","5.51","NON-STATE","mint record"),("B7","5.55","NON-STATE","mint record"),
 ("B7","5.57","NON-STATE","mint record"),("B7","5.58","NON-STATE","mint record"),
 ("B7","5.59","NON-STATE","mint record"),("B7","5.60","NON-STATE","mint record"),
 ("B10","5.2","COHERENT","'full derivation §5.2'"),
 ("B10","5.18","COHERENT","'anti-stuck floor, REQUIRED with it (§5.18)' — §5.18 open on the floor VALUE"),
 ("B12","5.52","NON-STATE","mint record"),("B12","5.53","NON-STATE","mint record"),("B12","5.54","NON-STATE","mint record"),
 ("B14","5.25","NON-STATE","mint record ('NEW: (vii) §5.25')"),
 ("B14","5.28","AMBIGUOUS","'the axis they are converted onto -> §5.28, decision A33' — §5.28 names TWO defects (§11.179(i)); this pre-2026-08-04 citation means the ARCHIVED one, and this §13-side citer is NOT covered by the three disambiguation notes F59's acceptance placed"),
 ("B14","5.49","NON-STATE","mint record"),
 ("B15","5.32","STALE","'Reference half closes with §5.32's one-site fix' — §5.32 CLOSED 2026-08-01 (F20, §11.128); the row carries no later block"),
 ("B17","5.26","NON-STATE","'Pre-existing §5.26 exposed'"),
 ("B18","5.80","COHERENT","'§5.80's converter unblock' — §5.80 still open"),
 ("B18","5.89","COHERENT","'B35 and §5.89 are INFORMED, not decided' — mirrored at §5.89's own row"),
 ("B18","5.100","NON-STATE","mint record"),("B18","5.101","NON-STATE","mint record"),
 ("B21","5.18","COHERENT","'ascend floored (§5.18 restored on live geometry)'"),
 ("B24","5.23","COHERENT","'grounded fold FIXED to parent spin en route — §5.23'"),
 ("B27","5.5","COHERENT","'Tier B reproduced by type, §5.5' — §11.163(c): 'B27's own §13 row records all of this correctly'"),
 ("B31","5.3","NOT-A-ROW","'§5.3's annotation mechanism' = b31-design.md §5.3 'Inline annotation (O7/O8)', not INTENT §5.3 (`notableBody`)"),
 ("B31","5.4","NOT-A-ROW","'b31-design.md §3.5/§4.2/§5.4/§7' = that document's own sections"),
 ("B31","5.27","COHERENT","T3/§5.27 sequencing SUPERSEDED in place by the row's 2026-08-26 blocks (T3 unblocked then RESOLVED, prediction refuted)"),
 ("B31","5.32","COHERENT","the save-permanence hazard is superseded by the row's own '§5.32 CLOSED' block"),
 ("B31","5.37","COHERENT","'§5.37's suspended galactic load' — a named boundary (archived-read, flagged)"),
 ("B31","5.39","COHERENT","'§5.39's parser unification is a PRECONDITION' (archived-read, flagged)"),
 ("B31","5.41","COHERENT","§5.41 open"),("B31","5.42","COHERENT","§5.42 open"),
 ("B31","5.63","COHERENT","the T1 clause is SUPERSEDED in place by the row's '[§5.63 CLOSED 2026-08-01 ...]' block"),
 ("B31","5.104","COHERENT","mint record inside the T3-RESOLVED block; §5.104's closure is F41's, recorded at §5.104"),
 ("B33","5.41","COHERENT","§5.41 open"),("B33","5.42","COHERENT","§5.42 open"),("B33","5.68","COHERENT","§5.68 open"),
 ("B34","5.66","COHERENT","§5.66 open"),("B34","5.68","COHERENT","§5.68 open"),("B34","5.69","NON-STATE","mint record"),
 ("B34","5.70","NON-STATE","mint record"),("B34","5.71","NON-STATE","mint record"),
 ("B35","5.89","COHERENT","'§5.89 ... the row keeps its item and loses one of its reasons'"),
 ("B38","5.36","COHERENT","'media subtitle toggle tests the wrong variable -> §5.36' — §5.36 open"),
 ("B39","5.31","COHERENT","'§5.31 CLOSED on its own discriminator' (archived-read, flagged)"),
 ("B39","5.44","COHERENT","'§5.44 impossible here' — and this is what makes §5.44's own text STALE on the forward axis"),
 ("B39","5.46","STALE","'publishParkedFrame keeping the parent frame the up-chain never caches (-> §5.46)' — §5.46 FIXED 2026-08-09 (F29, §11.139): the up-chain now writes matLocalToBodyPos at both sites, so the relative clause is false at HEAD"),
 ("B39","5.99","COHERENT","'Cause of the misreading -> §5.99' — §5.99 live"),
]
import collections, sys
out=open('/home/claude/spacecrafter/claude/harness/artifacts/f60/f60_verdicts.tsv','w',encoding='utf-8')
out.write("dir\tsource\ttarget\ttgtclass\tverdict\treading\tground\n")
for s,t,k,v,r,g in V: out.write(f"FWD\t{s}\t{t}\t{k}\t{v}\t{r}\t{g}\n")
for s,t,v,g in B: out.write(f"BWD\t{s}\t{t}\t-\t{v}\t-\t{g}\n")
out.close()
print("FORWARD pairs:",len(V))
print(collections.Counter(v for _,_,_,v,_,_ in V))
print("reading:",collections.Counter(r for _,_,_,_,r,_ in V))
print("BACKWARD pairs:",len(B))
print(collections.Counter(v for _,_,v,_ in B))
