#!/usr/bin/env python3
"""Mechanical census of `dumpread`'s importers and their class - generated,
never a recalled list (Q-67).

    cd claude/harness && python3 artifacts/f101/importers.py > artifacts/f101/importers.md

THE FIRST VERSION OF THIS SCRIPT WAS WRONG IN EXACTLY THE WAY IT REPORTS: it
anchored the pattern with `^`, which drops the two importers that
`import dumpread` INSIDE a function (`f95_soak.py`, `artifacts/f98/f98_repro14.py`)
- i.e. precisely the two CENSUS readers this task had to opt out of the new
guard.  The pattern below is the dispatch section's own, unanchored, and its
residual blind spot is NAMED rather than fixed: unanchored, it also counts a
file that only mentions the words in a comment, so the `calls` column - not the
row's existence - is what carries weight.
"""
import glob
import os
import re

PAT = re.compile(r'import dumpread|from dumpread')


def main():
    files = sorted(set(p for p in glob.glob('**/*.py', recursive=True)
                       if PAT.search(open(p, errors='replace').read())))
    flat = sorted(p for p in files if os.sep not in p)
    extra = [p for p in files if p not in flat]
    print("# F101 - `dumpread` importers, classed\n")
    print("Generated by `artifacts/f101/importers.py`; the pattern is the "
          "dispatch section's own.\n")
    print("The section's census is `grep -l -E 'import dumpread|from dumpread' "
          "harness/*.py` and counts **%d** files here (the dispatch's PREMISES "
          "line says 22 and it PASSed; this run is after F101 added two of its "
          "own). The same pattern applied RECURSIVELY under `harness/` counts "
          "**%d**, and the %d it adds are %s. The load-bearing one is "
          "`artifacts/f98/f98_repro14.py`: it calls `dumpread.load_dump` and "
          "reads dumps whose old half is empty, so a census that stops at the "
          "directory's own level cannot see the caller this guard would have "
          "broken.\n"
          % (len(flat), len(files), len(extra),
             ", ".join("`%s`" % p for p in extra)))
    print("| file | `dumpread.load_dump` calls | class | how |")
    print("|---|---|---|---|")
    for p in files:
        src = open(p, errors='replace').read()
        calls = len(re.findall(r'dumpread\.load_dump\(', src))
        optout = 'require_old=False' in src
        own = re.search(r'^def load_dump\(', src, re.M) is not None
        if p.endswith('selftest_mutant.py'):
            cls, how = ("GUARD'S OWN MUTATION HARNESS",
                        "replaces `load_dump` to show the self-test can fail")
        elif calls == 0:
            cls = "GRAMMAR-ONLY - unaffected"
            how = ("defines its OWN record-level `load_dump`, sharing only the "
                   "grammar" if own else
                   "imports `loads`/`sanitize_nonfinite`/`unquote_nonfinite` "
                   "only")
        elif optout:
            cls = "**CENSUS - opts out**"
            how = "`require_old=False`, reason at the call"
        else:
            cls = "COMPARISON - keeps the default"
            how = "reads `pairs` (or the header) for a two-path comparison"
        print("| `%s` | %d | %s | %s |" % (p, calls, cls, how))


if __name__ == "__main__":
    main()
