#!/usr/bin/env python3
"""F104 -- slice the tree's own solver out of orbit.cpp, build it standalone,
measure it.  INTENT 5.145 / 11.223(b).

Why a slice and not a link: `orbit.cpp` includes body.hpp, protosystem.hpp and
ModularBody.hpp, so linking it standalone means stubbing the engine.  Why a
slice and not a copy (f102's shape): a copy drifts silently.  This module
EXTRACTS `EllipticalOrbit::eccentricAnomaly` from the tree at build time,
brackets it into a free function, records the slice's md5, and compiles it into
`f104_solver.cpp` -- which prints that md5 at every run, so a number can always
be traced to the exact source text that produced it.  `IterativeEll` /
`IterativeHyp` are included FOR REAL from the tree's header; nothing is copied.

  usage
    ./f104_solver.py build  <outdir> [--src ROOT]
    ./f104_solver.py time   <outdir> [--n 20000000]
    ./f104_solver.py corpus <outdir> [--census census.json] [--calls 20]
    ./f104_solver.py all    <outdir> [...]
"""
import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent.parent / "src"
SIG = "double EllipticalOrbit::eccentricAnomaly(double M, double &lastE) const"
# F107: the SECOND slice, for --replay.  `positionAtE` is what turns a solver
# residual into AU, and a residual in radians cannot be compared with a landed
# dump.  It is sliced (not mirrored) for the same reason the solver is: the
# number must name the source text that produced it.  Its members are bound by
# wrapping the body in a struct whose FIELD NAMES are the class's own -- the
# same trick the solver slice uses on `eccentricity` (a parameter there).
SIG_POS = "Vec3d EllipticalOrbit::positionAtE(double E) const"
SIGN_FN = """static double f104_sign(double x)
{
\tif (x < 0.)
\t\treturn -1.;
\telse if (x > 0.)
\t\treturn 1.;
\telse
\t\treturn 0.;
}
"""


def slice_body(src_root, sig=SIG):
    """The text between the signature's opening brace and its matching close."""
    path = Path(src_root) / "bodyModule" / "orbit.cpp"
    text = path.read_text(errors="strict")
    i = text.find(sig)
    if i < 0:
        raise SystemExit("f104_solver: signature not found in %s" % path)
    j = text.index("{", i)
    depth, k = 0, j
    while k < len(text):
        if text[k] == "{":
            depth += 1
        elif text[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    body = text[j:k + 1]
    # `sign` is a file-static of orbit.cpp; rename the CALLS, not the slice's
    # own arithmetic, so the slice stays byte-faithful apart from that token.
    used = body.replace("sign(", "f104_sign(")
    return body, used, str(path)


def generate(outdir, src_root):
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    body, used, path = slice_body(src_root)
    md5 = hashlib.md5(body.encode()).hexdigest()[:8]
    # F107: the position slice, hashed SEPARATELY so that F104_ECC_MD5 - which
    # every --sweep/--corpus/--converge line prints - keeps naming exactly the
    # text it named before this mode existed (the F107 boundary: the outputs of
    # the landed modes stay byte-identical).
    pbody, pused, _ = slice_body(src_root, SIG_POS)
    pmd5 = hashlib.md5(pbody.encode()).hexdigest()[:8]
    inc = outdir / "f104_ecc.inc"
    inc.write_text(
        "// GENERATED by f104_solver.py -- do not edit.\n"
        "// slice: %s :: %s\n"
        "// md5(slice) = %s\n"
        "#define F104_ECC_MD5 \"%s\"\n"
        "%s\n"
        "static double f104_eccentricAnomaly(double eccentricity, double M, "
        "double &lastE)\n%s\n"
        "// slice: %s :: %s\n"
        "// md5(slice) = %s\n"
        "#define F104_POS_MD5 \"%s\"\n"
        "struct F104Ell {\n"
        "    double pericenterDistance, eccentricity, inclination,\n"
        "           ascendingNode, argOfPeriapsis;\n"
        "    Vec3d positionAtE(double E) const\n%s\n};\n"
        % (path, SIG, md5, md5, SIGN_FN, used,
           path, SIG_POS, pmd5, pmd5, pused))
    return md5, inc


def build(outdir, src_root):
    md5, inc = generate(outdir, src_root)
    exe = Path(outdir) / "f104_solver"
    cmd = ["g++", "-O2", "-std=c++20", "-I" + str(src_root), "-I" + str(outdir),
           "-o", str(exe), str(HERE / "f104_solver.cpp")]
    print("  " + " ".join(cmd))
    subprocess.run(cmd, check=True)
    steps = run(exe, ["--steps"]).strip()
    print("  slice md5 %s ; %s" % (md5, steps))
    return exe, md5, steps


def run(exe, args):
    r = subprocess.run([str(exe)] + args, capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit("f104_solver failed: %s%s" % (r.stdout, r.stderr))
    return r.stdout


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("mode", choices=["build", "time", "corpus", "all"])
    ap.add_argument("outdir")
    ap.add_argument("--src", default=str(SRC))
    ap.add_argument("--n", type=int, default=20000000)
    ap.add_argument("--calls", type=int, default=20)
    ap.add_argument("--census", default=str(HERE / "artifacts" / "f104" / "census.json"))
    a = ap.parse_args()
    out = Path(a.outdir)
    exe, md5, steps = build(out, a.src)
    lines = [steps]
    if a.mode in ("time", "all"):
        for e, label in ((0.1, "ell<0.2 fixed point"),
                         (0.4373709923163567, "ell0.2-0.9 Newton (Eris's e)"),
                         (0.95, "ell0.9-1 Laguerre-Conway")):
            lines.append(run(exe, ["--time", repr(e), str(a.n)]).strip()
                         + "   # " + label)
        lines.append(run(exe, ["--time-ell", "0.256821757166782", str(a.n)]).strip()
                     + "   # IterativeEll (Juno's e)")
        lines.append(run(exe, ["--time-hyp", "1.5", str(a.n)]).strip()
                     + "   # IterativeHyp (no corpus body)")
    if a.mode in ("corpus", "all"):
        rows = json.load(open(a.census))["rows"]
        tsv = out / "corpus.tsv"
        with open(tsv, "w") as f:
            for n in sorted(rows):
                r = rows[n]
                if r["solver"] == "ITER":
                    f.write("%s\t%.17g\t%s\n" % (n, r["e"], r["branch"]))
        lines.append(run(exe, ["--corpus", str(tsv), str(a.calls)]).rstrip())
    txt = "\n".join(x for x in lines if x) + "\n"
    (out / "solver.txt").write_text(txt)
    print(txt)
    return 0


if __name__ == "__main__":
    sys.exit(main())
