#ifndef CORE_COMMON_HPP
#define CORE_COMMON_HPP

enum class SKYLINE_TYPE : char {
		LINE_CIRCLE_POLAR,
		LINE_POINT_POLAR,
		LINE_ECLIPTIC_POLE,
		LINE_GALACTIC_POLE,
		LINE_ANALEMMA,
		LINE_ANALEMMALINE,
		LINE_CIRCUMPOLAR,
		LINE_GALACTIC_CENTER,
		LINE_VERNAL,
		LINE_GREENWICH,
		LINE_ARIES,
		LINE_EQUATOR,
		LINE_GALACTIC_EQUATOR,
		LINE_MERIDIAN,
		LINE_TROPIC,
		LINE_ECLIPTIC,
		LINE_PRECESSION,
		LINE_VERTICAL,
		LINE_ZODIAC,
		LINE_ZENITH,
		LINE_UNKNOWN
	};

enum class SKYGRID_TYPE : char {
	GRID_EQUATORIAL,
	GRID_ECLIPTIC,
	GRID_GALACTIC,
	GRID_ALTAZIMUTAL,
	GRID_UNKNOWN
};

//structure qui stocke les grilles à un instant t
struct SkyGridSave {
	bool equatorial;
	bool ecliptic;
	bool galactic;
	bool altazimutal;
};

enum class SKYDISPLAY_TYPE : char{
	SKY_PERSON,
	SKY_NAUTIC,
	SKY_ORTHODROMY,
	SKY_LOXODROMY,
	SKY_COORDS,
	SKY_UNKNOWN
};

enum class SKYDISPLAY_NAME : char{
	SKY_PERSONAL,
	SKY_PERSONEQ,
	SKY_NAUTICAL,
	SKY_NAUTICEQ,
	SKY_ORTHODROMY,
	SKY_LOXODROMY,
	SKY_OBJCOORDS,
	SKY_MOUSECOORDS,
	SKY_ANGDIST
};

#endif