#ifndef CORE_COMMON_HPP
#define CORE_COMMON_HPP

enum SKYLINE_TYPE : char {
		LINE_CIRCLE_POLAR,
		LINE_POINT_POLAR,
		LINE_ECLIPTIC_POLE,
		LINE_GALACTIC_POLE,
		LINE_ANALEMMA,
		LINE_ANALEMMALINE,
		LINE_CIRCUMPOLAR,
		LINE_GALACTIC_CENTER,
		LINE_VERNAL,
		LINE_GREENWICH,
		LINE_ARIES,
		LINE_EQUATOR,
		LINE_GALACTIC_EQUATOR,
		LINE_MERIDIAN,
		LINE_TROPIC,
		LINE_ECLIPTIC,
		LINE_PRECESSION,
		LINE_VERTICAL,
		LINE_ZODIAC,
		LINE_ZENITH,
		LINE_UNKNOWN
	};

enum SKYGRID_TYPE : char {
	GRID_EQUATORIAL,
	GRID_ECLIPTIC,
	GRID_GALACTIC,
	GRID_ALTAZIMUTAL,
	GRID_UNKNOWN
};

#endif