// the configured options and settings 
// do not edit this file


#ifndef _CONFIG_H_
#define _CONFIG_H_

#define PACKAGE  "spacecrafter"
#define VERSION "20.05.28"
#define APP_NAME "spacecrafter 20.05.28"
#define APP_LOWER_NAME "spacecrafter"
#define USER_NAME "AssociationSirius"
#define USER_EDITION "Proto"

#endif
