/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-108018-g2ed5925e26-20220905"
#endif /* AVUTIL_FFVERSION_H */
