// the configured options and settings 
// do not edit this file


#ifndef _CONFIG_H_
#define _CONFIG_H_

#define PACKAGE  "spacecrafter"
#define VERSION "21.08.24"
#define APP_NAME "spacecrafter 21.08.24"
#define APP_LOWER_NAME "spacecrafter"
#define USER_NAME "LSS Open Project"
#define USER_EDITION "Linux Edition Vulkan 2021"

#endif
